#!/bin/bash

set -eux

if ! command -v brew >/dev/null 2>&1; then
  echo "Install homebrew first!" >&2
  exit 1
fi

brew analytics off

# core; replace default/outdated versions in MacOS
brew install coreutils
brew install stow
brew install bash
brew install git
brew install less

# cli
brew install fish
brew install neovim
brew install tmux
brew install htop
brew install brew-cask-completion
brew install starship
brew install fd
brew install exa
brew install ripgrep
brew install fzf
brew install nnn
brew install bat
brew install tldr
brew install jq

# dev
brew install shellcheck
brew install git-delta
brew install direnv
brew install asdf
brew install tokei

# mics
brew install dimentium/autoraise/autoraise
brew install lolcat
brew install cowsay

# Casks
brew install --cask vivaldi
brew install --cask iterm2
brew install --cask hammerspoon
brew install --cask bettertouchtool
brew install --cask mos
brew install --cask karabiner-elements
brew install --cask iina
brew install --cask coteditor
brew install --cask visual-studio-code
brew install --cask telegram-desktop
brew install --cask wechat
brew install --cask bitwarden
brew install --cask nextcloud
brew install --cask itsycal
brew install --cask stats
brew install --cask maccy
brew install --cask macs-fan-control
brew install --cask homebrew/cask-fonts/font-jetbrains-mono-nerd-font
brew install --cask homebrew/cask-fonts/font-iosevka-nerd-font
