#!/usr/bin/env bash

# Link, unlink, or relink dotfiles

set -eu

# Text colors
color_reset='\033[0m'
color_green='\033[1;32m'
color_red='\033[1;31m'

usage() {
  echo "Usage: $0 <link | relink | unlink> <config file>"
  exit 1
}

DOTFILES_PATH="$(dirname "$(realpath "$0")")"
PACKAGES_PATH="$DOTFILES_PATH/packages"

main() {
  local action="$1"
  local conf="$2"

  if [[ -z "$action" || -z "$conf" ]]; then
    usage
  fi

  if [[ "$action" != stow && "$action" != delete && "$action" != restow ]]; then
    usage
  fi

  while read -r package; do
    if test -d "$PACKAGES_PATH/$package"; then
      echo -e "Package: ${color_green}${package}${color_reset}"
      ## --no-folding: don't symlink directories, create parent directories as needed
      stow --"$action" --no-folding --dir="$PACKAGES_PATH" --target="$HOME" --"$package"
    else
      echo -e "No such package ${color_red}${package}${color_reset}"
    fi
  done <"$conf"
}

main "$@"
