#!/usr/bin/env bash

# Stow, unstow, or restow dotfiles

set -eu

usage() {
  echo "Usage: $0 <stow | delete | restow> <config file>"
  exit 1
}

# Text colors
color_reset='\033[0m'
color_green='\033[1;32m'
color_red='\033[1;31m'

DOTFILES_PATH="$(dirname "$0")"
PACKAGES_PATH="$DOTFILES_PATH/packages"

main() {
  if [[ "$#" != 2 ]]; then
    usage
  fi

  local action="$1"
  local conf="$2"

  if [[ "$action" != stow && "$action" != delete && "$action" != restow ]]; then
    usage
  fi

  while read -r package; do
    if test -d "$PACKAGES_PATH/$package"; then
      echo -e "Package: ${color_green}${package}${color_reset}"
      ## --no-folding: don't symlink directories, create parent directories as needed
      stow --"$action" "$package" --no-folding --dir="$PACKAGES_PATH" --target="$HOME" --verbose=1
    else
      echo -e "No such package ${color_red}${package}${color_reset}"
    fi
  done <"$conf"
}

main "$@"
