#!/bin/bash

set -eux

if ! command -v brew >/dev/null 2>&1; then
  echo "Install homebrew first!" >&2
  exit 1
fi

brew analytics off

formulae=(
# core; replace default/outdated versions in MacOS
coreutils
stow
bash
git
less

# tools
fish
neovim
tmux
htop
brew-cask-completion
starship
fd
eza
ripgrep
fzf
nnn
bat
tealdeer # tldr
jq
dasel
lnav
git-delta
direnv
asdf
tokei

# mics
lolcat
cowsay
)

brew install "${formulae[@]}"
