#!/bin/bash

set -eux

if ! command -v brew >/dev/null 2>&1; then
  echo "Install homebrew first!" >&2
  exit 1
fi

casks=(
iterm2
hammerspoon
mos
karabiner-elements
iina
coteditor
visual-studio-code
bitwarden
itsycal
stats
monitorcontrol
font-jetbrains-mono-nerd-font
font-iosevka-nerd-font
)

brew install --cask "${casks[@]}"
