#!/bin/sh

# Autostart programs
~/bin/kbconfig &
/usr/bin/sxhkd &
/usr/bin/udiskie --no-automount --notify --tray &
/usr/bin/dunst &
/usr/bin/greenclip daemon &
/usr/bin/nm-applet &
/usr/bin/compton -f --vsync --inactive-dim 0.1 &
/usr/bin/feh --bg-scale --randomize --no-fehbg ~/Pictures/Wallpapers/* &
/usr/bin/flameshot &
/usr/bin/nextcloud &

# DE/WM
exec i3
