[character]
vicmd_symbol = "[N](bold green) "

[status]
disabled = false
format = "[$status]($style) "

[directory]
truncate_to_repo = false
fish_style_pwd_dir_length = 1

# Nerd Font Icons
[aws]
symbol = " "

[battery]
full_symbol = " "
charging_symbol = " "
discharging_symbol = " "

[conda]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[gcloud]
disabled = true

[golang]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

