set -xg theme_display_git yes
set -xg theme_display_git_dirty yes
set -xg theme_display_git_untracked yes
set -xg theme_display_git_ahead_verbose yes
set -xg theme_display_git_dirty_verbose yes
set -xg theme_display_git_stashed_verbose yes
set -xg theme_display_git_master_branch yes
set -xg theme_git_worktree_support no
set -xg theme_display_vagrant yes
set -xg theme_display_docker_machine yes
set -xg theme_display_k8s_context yes
set -xg theme_display_hg yes
set -xg theme_display_virtualenv yes
set -xg theme_display_ruby yes
set -xg theme_display_user ssh
set -xg theme_display_hostname ssh
set -xg theme_display_vi yes
set -xg theme_display_date yes
set -xg theme_display_cmd_duration yes
set -xg theme_title_display_process yes
set -xg theme_title_display_path yes
set -xg theme_title_display_user yes
set -xg theme_title_use_abbreviated_path no
set -xg theme_date_format "+%a %H:%M"
set -xg theme_avoid_ambiguous_glyphs yes
set -xg theme_powerline_fonts yes
set -xg theme_nerd_fonts yes
set -xg theme_show_exit_status yes
set -xg theme_color_scheme dark
set -xg fish_prompt_pwd_dir_length 0
set -xg theme_project_dir_length 0
set -xg theme_newline_cursor yes
